apps/product/urls.py
# purchase/urls.py
from django.urls import path

from . import views
app_name = "product"
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product-list'),
    path('scrap-now', views.ProductScrapView.as_view(),  name='product-scrap'),
]

django_docker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('products/', include('apps.product.urls')),
]

django_scraper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('products/', include('apps.product.urls')),
]

apps/product/models.py
import jsonfield
from django.db import models
from model_utils.models import TimeStampedModel, SoftDeletableModel


class Category(SoftDeletableModel, TimeStampedModel):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(SoftDeletableModel, TimeStampedModel):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255, unique=True)
    price = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    currency = models.CharField(max_length=50)
    summary = jsonfield.JSONField()

    class Meta:
        indexes = [
            models.Index(fields=['title']),
        ]

    def __str__(self):
        return self.title

apps/source/models.py
import jsonfield
from django.db import models
from model_utils.models import TimeStampedModel, SoftDeletableModel


class Source(SoftDeletableModel, TimeStampedModel):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=500, unique=True)
    # TODO::need to implement them in future to make it generic
    # category_selector = models.CharField(max_length=500)
    # subcategory_selector = models.CharField(max_length=500)
    # subcategory_selector = models.CharField(max_length=500)
    # title_selector = models.CharField(max_length=500)
    # price_selector = models.CharField(max_length=500)
    # currency_selector = models.CharField(max_length=500)
    # summary_selector = models.CharField(max_length=500)

    def __str__(self):
        return self.name

apps/product/forms.py
from django import forms

from apps.product.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [ 'title', 'category', 'price', 'summary']

apps/product/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views import View

from apps.product.forms import ProductForm
from apps.product.models import Product
from apps.source.tasks import scrap_product


class ProductListView(View):
    def get(self, request):
        products = Product.objects.filter().order_by('-id')
        # TODO:: take pagination limit from .env
        pagination = Paginator(products, 30)
        context = {'products': pagination.get_page(request.GET.get('page'))}

        return render(request, 'product/product-list.html', context=context)


class ProductScrapView(View):
    def get(self, request):
        scrap_product.delay()
        return redirect('product:product-list')

apps/source/views.py
from celery import current_app

# Create your views here.
from django.views import View


class TaskView(View):
    def get(self):
        pass

    @staticmethod
    def test_task(value='wasim'):
        print('was')
        b = current_app.send_task(
            'task_list_2',
            args=(value,),
            queue='default'
        )

        c = current_app.send_task(
            'task_list_2',
            args=('value',),
            queue='single_queue'
        )
        print(b.status, c.status)

apps/product/templates/product/base.html
{% extends 'base.html' %}

apps/product/templates/product/product-details.html
{% extends 'base.html' %}
{% load i18n crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h4>Product</h4>
                                <hr>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <span>Category: {{ product.category }}</span>
                                <br>
                                <span>Name: {{ product.name }}</span>
                                <br>
                                <span>Code: {{ product.code }}</span>
                                <br>
                                <span>Unit Price: {{ product.unit_price }}</span>
                                <br>
                                <span>Stock: {{ product.stock }} {{ product.unit_type }}</span>
                                <br>
                                <span>Brand: {{ product.brand }}</span>
                                <br>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/product/templates/product/product-list.html
{% extends 'product/base.html' %}

{% block extracss %}
    <style>
        label {
            text-align: right;
            display: block;
            margin: 5px;
            padding-bottom: 4px;
            padding-left: 10px;
        }

        .admin-search {
            border: 1px solid #c2cad8;
            height: 32px;

        }

        .dateinput.form-control {
            width: 80%;
        }
    </style>
{% endblock extracss %}
{% block content %}
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <div class="header-right">
                        <form action="" class="search nav-form">
                            <div class="row">
                                <div class="col-sm-6">
                                    <a class="btn btn-primary" href="{% url 'product:product-scrap' %}">Scrap now
                                        Product</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center g-mb-20">
        <div class="col-md-12">
            <!-- Table Striped Rows -->
            <div class="table-responsive">
                <h4>Product List</h4>

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Price</th>
                        <th>Summary</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for product in products %}
                        <tr>
                            <td>{{ product.title }}</td>
                            <td>{{ product.price }}{{ product.currency }}</td>
                            <td>
                                {{product.summary}}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>

            {% if products.has_other_pages %}

                {% include 'basic/pagination.html' with objects=products %}
            {% endif %}

        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script>
        {#$(document).on('ready', function () {#}
        {##}
        {#  $('#time_range_select').selectpicker();#}
        {#  $('#time_range_select').on('change', function (e) {#}
        {#    console.log(this.value,#}
        {#      this.options[this.selectedIndex].value,#}
        {#      $(this).find("option:selected").val(),);#}
        {#    $(this).closest('form').submit();#}
        {##}
        {#  });#}
        {#  $('#id_from_date').datetimepicker({#}
        {#    format: 'YYYY-MM-DD'#}
        {#  });#}
        {#  $('#id_to_date').datetimepicker({#}
        {#    format: 'YYYY-MM-DD'#}
        {#  });#}
        {##}
        {#})
        ;
        #}

    </script>
{% endblock extrajs %}

apps/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

apps/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Scraper{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

      <!-- Latest compiled and minified Bootstrap CSS -->
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">


      <!-- Your stuff: Third-party CSS libraries go here -->

      <!-- This file stores project-specific CSS -->

      <link href="{% static 'css/project.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">


    {% endblock %}
    {% block compressed-css %}
    {% endblock compressed-css %}
    {% block extra_css %}
    {% endblock extra_css %}

</head>

<body>

{% include "basic/navigation.html" %}

{% block navigation %}
{% endblock navigation %}

{% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

    {% endfor %}
{% endif %}
<div class="container">
    {% block content %}

    {% endblock %}
</div>

{% block content_extra %}
{% endblock %}

{% block extra_body %}
{% endblock %}

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}

  <!-- Bootstrap JS and its dependencies-->
  <script src="{% static 'vendor/jquery/jquery.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'vendor/popper/popper.min.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->


  <!-- place project specific Javascript in this file -->

  <script src="{% static 'js/project.js' %}"></script>


{% endblock javascript %}
{% block extra_js %}
{% endblock extra_js %}
</body>
</html>

apps/templates/basic/navigation.html
<!-- Navigation -->
{% block navigation %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {#        <a class="navbar-brand" href="#">Home</a>#}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="p-2"><a href="{% url 'product:product-list' %}">Products</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

<!--                {% if user.is_authenticated %}-->
<!--                    <li class="p-2"><a href="{% url 'account_logout' %}"><i class="fa fa-log-out" aria-hidden="true"></i>Logout</a>-->
<!--                    </li>-->
<!--                {% else %}-->
<!--                    &emsp;<li class="p-2"><a href="{% url 'account_login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>-->
<!--                    </li>-->
<!--                {% endif %}-->
            </ul>

        </div>
    </nav>
{% endblock navigation %}

apps/templates/basic/pagination.html
{% load query_parameters %}

<nav aria-label="...">

  <ul class="pagination">
    {% if objects.has_previous %}
      <li class="page-item"><a class="page-link"
                               href="?{% set_query_parameters page=1 %}">&laquo;</a>
      </li>
      <li class="page-item"><a class="page-link"
                               href="?{% set_query_parameters page=objects.previous_page_number %}">&lsaquo;</a>
      </li>
      <li class="page-item"><a class="page-link" href="?{% set_query_parameters page=1 %}">1</a></li>

    {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}

    {% for i in objects.paginator.page_range %}
      {% if i < objects.number and i >= objects.number|add:"-4" and i != objects.number and i != 1 %}
        <li class="page-item"><a class="page-link"
                                 href="?{% set_query_parameters page=i %}">{{ i }}</a></li>
      {% elif i > objects.number and i <= objects.number|add:"4" and i != objects.number and i != objects.paginator.num_pages %}
        <li class="page-item"><a class="page-link"
                                 href="?{% set_query_parameters page=i %}">{{ i }}</a></li>
      {% elif objects.number == i %}
        <li class="page-item active"><a class="page-link"
                                        href="?{% set_query_parameters page=i %}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if objects.has_next %}
      <li class="page-item"><a class="page-link"
                               href="?{% set_query_parameters page=objects.paginator.num_pages %}">{{ objects.paginator.num_pages }}</a>
      </li>

      <li class="page-item"><a class="page-link"
                               href="?{% set_query_parameters page=objects.next_page_number %}">&rsaquo;</a>
      </li>
      <li class="page-item"><a class="page-link"
                               href="?{% set_query_parameters page=objects.paginator.num_pages %}">&raquo;</a>
      </li>

    {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
</nav>